version: '3.8'

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mit-app-client
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true # Tương đương với -i trong docker run
    tty: true        # Tương đương với -t trong docker run 